[project]
name = "mplDTs"
version = "2.1.0"
description = "Set of tools to produce CMS DTs matplotlib patches"
authors = [
  { name = "Daniel Estrada", email = "destrada@cern.ch" }
]
maintainers = [
  { name = "Daniel Estrada", email = "destrada@cern.ch" }
]
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "pandas>=2.2",
    "matplotlib>=3.9.3",
    "mplhep>=0.3",
    "pytransform3d>=3.14.0"
]

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx-copybutton"
]
dev = [
    "black"
]

[project.urls]
Documentation = "https://danielestrada971102.github.io/mplDTs/"
Repository = "https://github.com/DanielEstrada971102/mplDTs"

[tool.setuptools.packages.find]
where = ["."]
include = ["mpldts*"]

[tool.setuptools.package-data]
"mpldts.geometry" = ["*.xml"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
